package com.derun.webservice.client.taxmonitor;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2015-08-13T19:03:05.986+08:00
 * Generated source version: 2.6.0
 * 
 */
@WebService(targetNamespace = "http://service.taxmonitor.derun.com", name = "TaxMonitorServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface TaxMonitorServicePortType {

    @WebResult(name = "out", targetNamespace = "http://service.taxmonitor.derun.com")
    @RequestWrapper(localName = "taxMon", targetNamespace = "http://service.taxmonitor.derun.com", className = "com.derun.webservice.client.taxmonitor.TaxMon")
    @WebMethod
    @ResponseWrapper(localName = "taxMonResponse", targetNamespace = "http://service.taxmonitor.derun.com", className = "com.derun.webservice.client.taxmonitor.TaxMonResponse")
    public com.derun.webservice.client.taxmonitor.BaseMonitorResInfo taxMon(
        @WebParam(name = "in0", targetNamespace = "http://service.taxmonitor.derun.com")
        com.derun.webservice.client.taxmonitor.BaseMonitorReqInfo in0
    );
}
